export default {
    "ADD_WEEK":"ADD_WEEK",
    "ADD_DAY":"ADD_DAY",
    "ADD_MEAL":"ADD_MEAL",
    "ADD_RECIPE":"ADD_RECIPE",

    // Ingredients
    "ADD_INGREDIENT":"send/ADD_INGREDIENT",
    "RECEIVE_INGREDIENTS":"RECEIVE_INGREDIENTS",
    "SELECT_INGREDIENT":"SELECT_INGREDIENT",



    "REMOVE_WEEK":"REMOVE_WEEK",
    "REMOVE_DAY":"REMOVE_DAY",
    "REMOVE_MEAL":"REMOVE_MEAL",
    "REMOVE_RECIPE":"REMOVE_RECIPE",
    "REMOVE_INGREDIENT":"REMOVE_INGREDIENT"
}