export default {
    "ADD_WEEK":"ADD_WEEK",
    "ADD_DAY":"ADD_DAY",
    "ADD_MEAL":"ADD_MEAL",
    "ADD_RECIPE":"ADD_RECIPE",
    "ADD_INGREDIENT":"ADD_INGREDIENT",
    "REMOVE_WEEK":"REMOVE_WEEK",
    "REMOVE_DAY":"REMOVE_DAY",
    "REMOVE_MEAL":"REMOVE_MEAL",
    "REMOVE_RECIPE":"REMOVE_RECIPE",
    "REMOVE_INGREDIENT":"REMOVE_INGREDIENT"
}